version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    apt_packages:
        - graphviz
        - jupyter        

sphinx:
   configuration: docs/source/conf.py


python:
    install:
      - requirements: requirements.txt